#include <ti/driverlib/dl_flashctl.h>

#include "hdd_i2c_calibraton.h"

/* 8-bit data to write to flash */
uint8_t gData8 = 0x11;

/* 16-bit data to write to flash */
uint16_t gData16 = 0x2222;

/* 32-bit data to write to flash */
uint32_t gData32 = 0x33333333;

/* Array to write 64-bits to flash */
uint32_t gDataArray64[] = {0xABCDEF00, 0x12345678};

volatile DL_FLASHCTL_COMMAND_STATUS gCmdStatus;

/* Codes to understand where error occured */
#define NO_ERROR 0
#define ERROR_ERASE 1
#define ERROR_WRITE_8_BIT 2
#define ERROR_READ_8_BIT 3
#define ERROR_WRITE_16_BIT 4
#define ERROR_READ_16_BIT 5
#define ERROR_WRITE_32_BIT 6
#define ERROR_READ_32_BIT 7
#define ERROR_WRITE_64_BIT 8
#define ERROR_READ_64_BIT 9
#define ERROR_EXPECTED_FAIL 10
#define ERROR_UNEXPECTED 11
#define ERROR_WRITE_64_OVERRIDE 12
#define ERROR_READ_64_OVERRIDE 13
#define ERROR_EXPECTED_FAIL_OVERRIDE 14
#define ERROR_8BIT_W 2
#define ERROR_16BIT_W 3
#define ERROR_32BIT_W 4
#define ERROR_64BIT_W 5

volatile uint8_t gErrorType = NO_ERROR;
uint8_t test = 0;
bool hddI2CCalibrationInit(void) {
  /* Use explicit ULL suffix to ensure a 64-bit constant */
  // hddI2CWriteCalibrationData(0x0123456789ABCDEFULL);
  uint32_t low, high = 0;
  if (hddI2CReadCalibrationData(&low, &high) == false) {
    SEGGER_RTT_printf(0, "Failed to read back calibration data\n");
    return false;
  } else {
    SEGGER_RTT_printf(0, "Read back calibration data: 0x%x 0x%x \n", low, high);
  }
  return true;
}

bool hddI2CWriteCalibrationData(uint64_t calibrationData) {
  /* Unprotect sector in main memory with ECC generated by hardware */
  DL_FlashCTL_unprotectSector(FLASHCTL, MAIN_BASE_ADDRESS,
                              DL_FLASHCTL_REGION_SELECT_MAIN);
  /* Erase sector in main memory */
  gCmdStatus = DL_FlashCTL_eraseMemoryFromRAM(FLASHCTL, MAIN_BASE_ADDRESS,
                                              DL_FLASHCTL_COMMAND_SIZE_SECTOR);
  if (gCmdStatus == DL_FLASHCTL_COMMAND_STATUS_FAILED) {
    /* If command was not successful, set error flag */
    SEGGER_RTT_printf(0, "Flash erase failed during calibration init\n");
    gErrorType = ERROR_ERASE;
  } else {
    SEGGER_RTT_printf(0, "Flash erase succeeded during calibration init\n");
  }

  uint32_t low  = (uint32_t)(calibrationData & 0xFFFFFFFF);
  uint32_t high = (uint32_t)((calibrationData >> 32) & 0xFFFFFFFF);
  uint32_t gDataArray64[2] = {low, high};

  if (gErrorType == NO_ERROR) {
    /* 8-bit write to flash in main memory */
    DL_FlashCTL_unprotectSector(FLASHCTL, MAIN_BASE_ADDRESS,
                                DL_FLASHCTL_REGION_SELECT_MAIN);
    gCmdStatus = DL_FlashCTL_programMemoryFromRAM64WithECCGenerated(
        FLASHCTL, MAIN_BASE_ADDRESS, &gDataArray64[0]);
    if (gCmdStatus == DL_FLASHCTL_COMMAND_STATUS_FAILED) {
      /* If command was not successful, set error flag */
      SEGGER_RTT_printf(0, "Flash 64-bit write failed during calibration init\n");
      gErrorType = ERROR_64BIT_W;
    } else {
      SEGGER_RTT_printf(0, "Flash 64-bit write succeeded during calibration init\n");
      /* Wait for the flash controller to complete and then read back the
       * programmed words to verify the write. */
      DL_FlashCTL_waitForCmdDone(FLASHCTL);
      uint32_t *rb = (uint32_t *)MAIN_BASE_ADDRESS;
      uint32_t rb_low = rb[0];
      uint32_t rb_high = rb[1];
      SEGGER_RTT_printf(0, "Flash post-write readback: low=0x%08X high=0x%08X\n", rb_low, rb_high);
      if ((rb_low != low) || (rb_high != high)) {
        SEGGER_RTT_printf(0, "Flash verification failed: expected low=0x%08X high=0x%08X\n", low, high);
        gErrorType = ERROR_READ_64_OVERRIDE;
      }
    }
  }
  return (gErrorType == NO_ERROR);
}

bool hddI2CReadCalibrationData(uint32_t* low, uint32_t* high) {
  DL_FlashCTL_waitForCmdDone(FLASHCTL);

  uint32_t *ptr = (uint32_t *)MAIN_BASE_ADDRESS;

  *low  = ptr[0];
  *high = ptr[1];
  SEGGER_RTT_printf(0, "Read back from flash: low=0x%08X high=0x%08X\n", *low, *high);

  return true;
}